"use strict";
var assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
var api=require("../../co-reading-repository.js");
(async function(){
  var calls=[],client={rpc:function(name,args){calls.push([name,args]);var mutations=["disconnect_friend_connection","block_friend_connection","unblock_user","record_friend_rabbit_seen_v2"];return Promise.resolve({data:name==="get_friend_connections"?[{connection_id:"c2",friend_display_name:"둘",friend_intro:"두번째",connected_at:"2026-01-02",my_visit_state:"allowed"},{connection_id:"c1",friend_display_name:"하나",friend_intro:"첫번째",connected_at:"2026-01-01",my_visit_state:"undecided"}]:name==="get_friend_profile"?[{display_name:"하나",intro:"첫번째"}]:name==="get_blocked_users"?[{block_handle:"block-1",display_name:"차단 사용자",intro:"",blocked_at:"2026-01-01"}]:mutations.indexOf(name)!==-1?true:"ok",error:null});}};
  var r=api.create(client);
  calls=[];var existingInvite=await r.createInviteWithDisplayName("기존 이름","");
  assert.deepEqual(calls.map(function(x){return x[0];}),["create_friend_invite"],"an existing profile name must not be written again");
  assert.deepEqual(existingInvite,{token:"ok",displayName:"기존 이름"});
  calls=[];var savedLocally="";var firstInvite=await r.createInviteWithDisplayName("","새 이름",function(saved){savedLocally=saved;});
  assert.deepEqual(calls.map(function(x){return x[0];}),["set_friend_display_name","create_friend_invite"],"the first invite saves one profile name before creating the invite");
  assert.deepEqual(firstInvite,{token:"ok",displayName:"ok"});assert.equal(savedLocally,"ok");
  var failedCalls=[],failedName="",failedRepo=api.create({rpc:function(name){failedCalls.push(name);if(name==="set_friend_display_name")return Promise.resolve({data:"저장된 이름",error:null});return Promise.reject(new Error("invite failed"));}});
  await assert.rejects(failedRepo.createInviteWithDisplayName("","새 이름",function(saved){failedName=saved;}),/invite failed/);
  assert.equal(failedName,"저장된 이름","the saved profile name must reach local state before invite creation finishes");
  await assert.rejects(failedRepo.createInviteWithDisplayName(failedName,""),/invite failed/);
  assert.deepEqual(failedCalls,["set_friend_display_name","create_friend_invite","create_friend_invite"],"retry after invite failure must not save the profile name again");
  calls=[];
  await r.acceptInviteWithDisplayName("token","","새 친구");
  assert.deepEqual(calls.map(function(x){return x[0];}),["set_friend_display_name","accept_friend_invite"]);
  calls=[];await r.acceptInviteWithDisplayName("token","이미 있음","");assert.deepEqual(calls.map(function(x){return x[0];}),["accept_friend_invite"]);
  assert.deepEqual((await r.getConnections()).map(function(row){return row.connectionId;}),["c1","c2"]);
  await r.setConnectionVisit("c1",true);await r.disconnectConnection("c2");await r.recordRabbitSeenV2("c1");
  assert.deepEqual(calls.slice(-3).map(function(x){return x[0];}),["set_friend_connection_visit","disconnect_friend_connection","record_friend_rabbit_seen_v2"]);
  assert.deepEqual(await r.getFriendProfile("c1"),{displayName:"하나",intro:"첫번째"});
  await r.blockConnection("c1");await r.reportConnection("c1","spam","");
  assert.deepEqual(calls.slice(-2).map(function(x){return x[0];}),["block_friend_connection","report_friend_connection"]);
  assert.equal((await r.getBlockedUsers())[0].displayName,"차단 사용자");
  assert.equal((await r.getBlockedUsers())[0].handle,"block-1");
  await r.unblockUser("block-1");
  assert.deepEqual(calls[calls.length-1],["unblock_user",{p_block_handle:"block-1"}]);
  var falseRepo=api.create({rpc:function(){return Promise.resolve({data:false,error:null});}});
  await assert.rejects(falseRepo.blockConnection("c1"),/완료하지 못했어요/);
  assert.equal(api.isAlreadyConnectedError({code:"PT409"}),true);
  var cleared=0,ctx=api.createInviteContext("token",function(){cleared++;});
  assert.equal(ctx.consumeAutoNavigation(),true);assert.equal(ctx.consumeAutoNavigation(),false);
  ctx.clear();assert.equal(ctx.getToken(),"");assert.equal(cleared,1);
  var stored={},storage={getItem:function(key){return stored[key]||null;},setItem:function(key,value){stored[key]=value;},removeItem:function(key){delete stored[key];}};
  assert.equal(api.resolveInviteToken("invite-token",storage,"pending"),"invite-token");
  assert.equal(api.resolveInviteToken("",storage,"pending"),"invite-token");
  var storageCleared=0,persisted=api.createInviteContext("invite-token",null,function(){storage.removeItem("pending");storageCleared++;});persisted.clear();
  assert.equal(storage.getItem("pending"),null);assert.equal(storageCleared,1);
  assert.equal(api.resolveAuthRedirectUrl("https://rhthgus2660.github.io/booktokki/?friend_invite=secret","https://rhthgus2660.github.io/booktokki/"),"https://rhthgus2660.github.io/booktokki/");
  assert.equal(api.resolveAuthRedirectUrl("http://localhost:8000/?friend_invite=secret","https://rhthgus2660.github.io/booktokki/"),"http://localhost:8000/");
  var busy={working:false},resolve,executed=0;
  var first=api.runOnce(busy,"working",function(){executed++;return new Promise(function(r){resolve=r;});});
  var second=await api.runOnce(busy,"working",function(){executed++;});
  assert.equal(second.ignored,true);assert.equal(executed,1);resolve();await first;assert.equal(busy.working,false);
  var staleBusy={working:false},release;var staleWork=api.runOnce(staleBusy,"working",function(){return new Promise(function(r){release=r;});});await new Promise(function(r){setImmediate(r);});var newSessionMarker={};staleBusy.working=newSessionMarker;release();await staleWork;assert.equal(staleBusy.working,newSessionMarker,"an old session completion cannot clear a newer busy guard");
  var html=fs.readFileSync(path.join(__dirname,"../../index.html"),"utf8");
  assert.match(html,/friendRecipientName/);assert.match(html,/acceptInviteWithDisplayName/);
  assert.match(html,/이 초대는 만료됐거나 이미 사용됐어요/);assert.match(html,/data-friend-invite-later/);
  assert.match(html,/consumeAutoNavigation/);assert.match(html,/data-friend-share/);assert.match(html,/data-friend-copy/);
  assert.match(html,/coReadingInviteUrl/);assert.match(html,/AbortError/);assert.match(html,/runOnce\(state,"coReadingBusyCreate"/);assert.match(html,/runOnce\(state,"coReadingBusyAccept"/);
  assert.match(html,/getConnections\(\)/);assert.match(html,/coReadingConnections/);assert.match(html,/이미 연결된 친구예요/);
  assert.match(html,/내가 북토끼를 쓰는 동안에는 내 토끼도 이 친구의 서재에 나타날 수 있어요/);assert.match(html,/친구와 연결했어요/);
  assert.doesNotMatch(html,/이미 친구와 연결되어 있어요/);
  assert.match(html,/FRIEND_INVITE_PENDING_KEY/);assert.match(html,/resolveAuthRedirectUrl/);
  assert.doesNotMatch(html,/start_reading_presence|stop_reading_presence|setInterval\([^)]*presence/);
  var renderSource=html.slice(html.indexOf("function renderCoReading()"),html.indexOf("/* ---------------- modals ---------------- */"));
  function rendered(connections,name,nameOpen,status){var el={innerHTML:""},context={state:{coReadingConnections:connections,coReadingStatus:status||"ready",coReadingPreviewName:"",coReadingDisplayName:name===undefined?"나":name,coReadingInviteNameOpen:!!nameOpen,coReadingBusyConnections:{},coReadingBusyAccept:false,coReadingBusyCreate:false,coReadingInviteUrl:"",coReadingMessage:""},document:{getElementById:function(){return el;}},esc:function(x){return String(x);},friendVisitEnabled:function(){return true;},myHeader:function(){return "";}};vm.runInNewContext(renderSource+"\nrenderCoReading();",context);return el.innerHTML;}
  var empty=rendered([]);assert.match(empty,/아직 연결된 친구가 없어요/);assert.match(empty,/새로운 친구 초대/);
  var one=rendered([{connectionId:"one",friendDisplayName:"한 명",myVisitState:"allowed"}]);
  assert.equal((one.match(/data-friend-row=/g)||[]).length,1);assert.match(one,/data-friend-avatar/);assert.match(one,/data-friend-profile="one"/);assert.match(one,/data-friend-visit-toggle="one"/);
  var multi=rendered([{connectionId:"one",friendDisplayName:"한 명",myVisitState:"allowed"},{connectionId:"two",friendDisplayName:"두 명",myVisitState:"declined"}]);
  assert.equal((multi.match(/data-friend-row=/g)||[]).length,2);assert.match(multi,/친구 초대 링크 만들기/);assert.match(multi,/data-friend-visit-toggle="one"/);assert.match(multi,/data-friend-profile="two"/);assert.doesNotMatch(multi,/상대방의 설정/);assert.match(multi,/보고 있는 화면, 방문 이력과 마지막 사용 시각은 친구에게 보여주지 않아요/);
  assert.doesNotMatch(multi,/같이 읽을 친구로 연결되어 있어요/);assert.match(multi,/읽는 책, 페이지, 북로그는 공유되지 않아요/);
  assert.doesNotMatch(rendered([],"기존 이름"),/id="friendDisplayName"/);
  var unnamedClosed=rendered([],"",false);assert.match(unnamedClosed,/data-friend-invite/);assert.doesNotMatch(unnamedClosed,/id="friendDisplayName"/);
  var unnamedOpen=rendered([],"",true);assert.match(unnamedOpen,/친구에게 어떤 이름으로 보일까요/);assert.match(unnamedOpen,/id="friendDisplayName"/);assert.match(unnamedOpen,/data-friend-invite-continue/);assert.match(unnamedOpen,/북토끼 친구들에게 공통으로 보여요/);
  var errorView=rendered([],"",true,"error");assert.match(errorView,/다시 시도/);assert.match(errorView,/data-friend-retry/);assert.doesNotMatch(errorView,/새로운 친구 초대|id="friendDisplayName"|data-friend-invite/);
  console.log("PASS co-reading friend connection UI tests");
})().catch(function(e){console.error(e);process.exit(1);});
