"use strict";
var assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
var api=require("../../co-reading-repository.js");
(async function(){
  var calls=[],client={rpc:function(name,args){calls.push([name,args]);return Promise.resolve({data:name==="get_friend_connections"?[{connection_id:"c2",friend_display_name:"둘",connected_at:"2026-01-02",my_visit_state:"allowed"},{connection_id:"c1",friend_display_name:"하나",connected_at:"2026-01-01",my_visit_state:"undecided"}]:"ok",error:null});}};
  var r=api.create(client);
  await r.acceptInviteWithDisplayName("token","","새 친구");
  assert.deepEqual(calls.map(function(x){return x[0];}),["set_friend_display_name","accept_friend_invite"]);
  calls=[];await r.acceptInviteWithDisplayName("token","이미 있음","");assert.deepEqual(calls.map(function(x){return x[0];}),["accept_friend_invite"]);
  assert.deepEqual((await r.getConnections()).map(function(row){return row.connectionId;}),["c1","c2"]);
  await r.setConnectionVisit("c1",true);await r.disconnectConnection("c2");await r.recordRabbitSeenV2("c1");
  assert.deepEqual(calls.slice(-3).map(function(x){return x[0];}),["set_friend_connection_visit","disconnect_friend_connection","record_friend_rabbit_seen_v2"]);
  assert.equal(api.isAlreadyConnectedError({code:"PT409"}),true);
  var cleared=0,ctx=api.createInviteContext("token",function(){cleared++;});
  assert.equal(ctx.consumeAutoNavigation(),true);assert.equal(ctx.consumeAutoNavigation(),false);
  ctx.clear();assert.equal(ctx.getToken(),"");assert.equal(cleared,1);
  var stored={},storage={getItem:function(key){return stored[key]||null;},setItem:function(key,value){stored[key]=value;},removeItem:function(key){delete stored[key];}};
  assert.equal(api.resolveInviteToken("invite-token",storage,"pending"),"invite-token");
  assert.equal(api.resolveInviteToken("",storage,"pending"),"invite-token");
  var storageCleared=0,persisted=api.createInviteContext("invite-token",null,function(){storage.removeItem("pending");storageCleared++;});persisted.clear();
  assert.equal(storage.getItem("pending"),null);assert.equal(storageCleared,1);
  assert.equal(api.resolveAuthRedirectUrl("https://rhthgus2660.github.io/booktokki/?friend_invite=secret","https://rhthgus2660.github.io/booktokki/"),"https://rhthgus2660.github.io/booktokki/");
  assert.equal(api.resolveAuthRedirectUrl("http://localhost:8000/?friend_invite=secret","https://rhthgus2660.github.io/booktokki/"),"http://localhost:8000/");
  var busy={working:false},resolve,executed=0;
  var first=api.runOnce(busy,"working",function(){executed++;return new Promise(function(r){resolve=r;});});
  var second=await api.runOnce(busy,"working",function(){executed++;});
  assert.equal(second.ignored,true);assert.equal(executed,1);resolve();await first;assert.equal(busy.working,false);
  var staleBusy={working:false},release;var staleWork=api.runOnce(staleBusy,"working",function(){return new Promise(function(r){release=r;});});await new Promise(function(r){setImmediate(r);});var newSessionMarker={};staleBusy.working=newSessionMarker;release();await staleWork;assert.equal(staleBusy.working,newSessionMarker,"an old session completion cannot clear a newer busy guard");
  var html=fs.readFileSync(path.join(__dirname,"../../index.html"),"utf8");
  assert.match(html,/friendRecipientName/);assert.match(html,/acceptInviteWithDisplayName/);
  assert.match(html,/이 초대는 만료됐거나 이미 사용됐어요/);assert.match(html,/data-friend-invite-later/);
  assert.match(html,/consumeAutoNavigation/);assert.match(html,/data-friend-share/);assert.match(html,/data-friend-copy/);
  assert.match(html,/coReadingInviteUrl/);assert.match(html,/AbortError/);assert.match(html,/runOnce\(state,"coReadingBusyCreate"/);assert.match(html,/runOnce\(state,"coReadingBusyAccept"/);
  assert.match(html,/getConnections\(\)/);assert.match(html,/coReadingConnections/);assert.match(html,/이미 연결된 친구예요/);
  assert.match(html,/내가 북토끼를 쓰는 동안엔 내 토끼도 이 친구 홈에 놀러 가요/);assert.match(html,/친구와 연결했어요/);
  assert.doesNotMatch(html,/이미 친구와 연결되어 있어요/);
  assert.match(html,/FRIEND_INVITE_PENDING_KEY/);assert.match(html,/resolveAuthRedirectUrl/);
  assert.doesNotMatch(html,/start_reading_presence|stop_reading_presence|setInterval\([^)]*presence/);
  var renderSource=html.slice(html.indexOf("function renderCoReading()"),html.indexOf("/* ---------------- modals ---------------- */"));
  function rendered(connections){var el={innerHTML:""},context={state:{coReadingConnections:connections,coReadingStatus:"ready",coReadingPreviewName:"",coReadingDisplayName:"나",coReadingBusyConnections:{},coReadingBusyAccept:false,coReadingBusyCreate:false,coReadingInviteUrl:"",coReadingMessage:""},document:{getElementById:function(){return el;}},esc:function(x){return String(x);},friendVisitEnabled:function(){return true;},myHeader:function(){return "";}};vm.runInNewContext(renderSource+"\nrenderCoReading();",context);return el.innerHTML;}
  assert.match(rendered([]),/아직 연결된 친구가 없어요/);
  assert.equal((rendered([{connectionId:"one",friendDisplayName:"한 명",myVisitState:"allowed"}]).match(/data-friend-row=/g)||[]).length,1);
  var multi=rendered([{connectionId:"one",friendDisplayName:"한 명",myVisitState:"allowed"},{connectionId:"two",friendDisplayName:"두 명",myVisitState:"declined"}]);
  assert.equal((multi.match(/data-friend-row=/g)||[]).length,2);assert.match(multi,/초대 링크 만들기/);assert.match(multi,/data-friend-visit-toggle="one"/);assert.match(multi,/data-friend-disconnect="two"/);
  console.log("PASS co-reading friend connection UI tests");
})().catch(function(e){console.error(e);process.exit(1);});
